### ISSUE TITLE
[Bug] Adopt make React always rebuild the DOM.

### ISSUE THREAD

**Issue by xialvjun** [pedronauck/react-adopt#11]
Just like the title, which will consume too much. It's not acceptable.

[![Edit yqyjy9jvz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yqyjy9jvz)

Well, if I use `adopt` rather than `Adopt`, it's ok.

**Comment by renatorib** [comment]
Hey dude! This is really bad.
I'm working on it #12
