### ISSUE TITLE
Alias props.render to props.children

### ISSUE THREAD

**Issue by alidcastano** [pedronauck/react-adopt#22]
I'm trying to use this with Apollo, but props.children is a required prop

The workaround is:

```
const QueryContainer = adopt({
  someQuery: <ExampleQuery />{props.render}<ExampleQuery/>
})
```

But it's so uncessary to have to do this for all  components when props.children could easily be aliased. I'm not even sure why it isn't used as the default :)

**Comment by pedronauck** [comment]
You can do that:

```js
const QueryContainer = adopt({
  someQuery: ({ render }) => <ExampleQuery>{.render}</ExampleQuery>
})
```

**Comment by alidcastano** [comment]
The idea would be to not have to do the above for every component because with an alias props.children would already part of react-adopt 

so ideally you can just do this: 

const QueryContainer = adopt({
  someQuery: ExampleQuery
})
