### ISSUE TITLE
Support node LTS

### ISSUE THREAD

**Issue by denkristoffer** [pedronauck/react-adopt#8]
Hi @pedronauck 👋 This library looks good! However, I just tried to set it up on our production app which is running node LTS, currently 8.11.1. `react-adopt` requires node >= 9. I've only had a quick look at `react-adopt`'s source, but I didn't notice anything that shouldn't work with node 8. Do you think the version requirement can be loosened?

**Comment by pedronauck** [comment]
Hi @denkristoffer, thanks for the tip, I'll change that and make a new release 👍

**Comment by pedronauck** [comment]
@denkristoffer done [v0.2.3](https://github.com/pedronauck/react-adopt/releases/tag/v0.2.3)
